knp_paginator:
  page_range: 5                      # nombre de liens de page affichés
  default_options:
      page_name: page                # nom du paramètre de page dans l'URL
      sort_field_name: sort          # nom du paramètre de tri dans l'URL
      sort_direction_name: direction # nom du paramètre de direction dans l'URL
      distinct: true                 # résultats distincts (utile avec le tri)
  template:
    # pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # template pour la pagination (Bootstrap 5)
      pagination: '@KnpPaginator/Pagination/tailwind_pagination.html.twig'     # template custom pour la pagination tailwind 
      sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # template pour les liens triables
